---
version: '3'
services:
  consumer_app:
    build:
      context: "."
      dockerfile: "./consumer_app/Dockerfile"
    ports:
      - '8001:8001'
    links:
      - envoy
    depends_on:
      - envoy
    environment:
      UPSTREAM_ORIGIN: "http://envoy:10000"
  upstream_app:
    build:
      context: "."
      dockerfile: "./upstream_app/Dockerfile"
    ports:
      - '8002:8002'
  envoy:
    image: "envoyproxy/envoy:latest"
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - "./envoy/envoy.yaml:/etc/envoy/envoy.yaml"
    environment:
      loglevel: info
    links:
      - upstream_app
    depends_on:
      - upstream_app
