---
version: '3'
services:
  consumer_app:
    build:
      context: "."
      dockerfile: "./consumer_app/Dockerfile"
    ports:
      - '8001:8001'
    links:
      - upstream_app
    depends_on:
      - upstream_app
    environment:
      UPSTREAM_ORIGIN: "http://upstream_app:8002"
  upstream_app:
    build:
      context: "."
      dockerfile: "./upstream_app/Dockerfile"
    ports:
      - '8002:8002'
